export { CanvasEditorPage } from './pages/CanvasEditorPage.js'
export type { CanvasEditorPageProps } from './pages/CanvasEditorPage.js'
export { mapPluginApiError } from './lib/error-mapping.js'
export { pluginApi } from './lib/plugin-api.js'
export type { PluginApi } from './lib/plugin-api.js'
